module.exports = [
  'strapi::errors',
  { name: 'strapi::security', config: { contentSecurityPolicy: false } },
  {
    name: 'strapi::cors',
    config: {
      origin: [
        'http://localhost:1337',
        'http://localhost:5173',
        'http://localhost:5174',
        'http://localhost:8081',
        'http://localhost:3000',
        'http://localhost:19006',
        'http://127.0.0.1:1337',
        'http://127.0.0.1:5173',
        'http://127.0.0.1:5174',
        'http://127.0.0.1:8081',
        'http://127.0.0.1:3000',
      ],
      headers: ['Content-Type', 'Authorization', 'Origin', 'Accept'],
      methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'HEAD', 'OPTIONS'],
      credentials: true,
    },
  },
  'strapi::poweredBy',
  'strapi::logger',
  'strapi::query',
  'strapi::body',
  'strapi::session',
  'strapi::favicon',
  'strapi::public',
];
